language: r
cache: packages
warnings_are_errors: false

before_install:
  - apt-get update
  - apt-get install -y python3
  - Rscript -e 'install.packages("devtools"); devtools::install_github("rstudio/keras"); library(keras); install_keras()'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
