language: r
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libxml2-dev
      - python3

before_install:
  - Rscript -e 'install.packages("devtools"); devtools::install_github("rstudio/keras"); library(keras); install_keras()'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
