language: r
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libxml2-dev

before_install:
  - Rscript -e 'install.packages("devtools");'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
