---
title: "Spectral analysis of electroencephalography (EEG) signals"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Spectral_analysis_of_EEG_signals}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Electroencephalography

Electroencephalography (EEG) refers to all the methods of recording, analysis and interpretation of the electrical activity of the brain. 

# Example data

An example EDF file can be donwloaded using the following code:

```{r download_edf_hidden, include=FALSE}
if(!file.exists("15012016HD.edf")){
  download.file("http://cloud.frenchkpi.com/s/65cm6DMq7SYKQ6J/download", "15012016HD.edf", "wget", T)
}
```

```{r download_data_display, eval=FALSE}
download.file("http://cloud.frenchkpi.com/s/65cm6DMq7SYKQ6J/download", "15012016HD.edf", "wget", T)
```

The EDF file can be loaded using the edfReader library.

```{r read_edf}
library(edfReader)

h <- readEdfHeader("15012016HD.edf")

s <- readEdfSignals(h, signals = c("C3-M2"))
```

# Spectrogram

```{r spectrogram, fig.width = 7}
library(rsleep)

spectrogram(signal = s$signal,
            sRate = s$sRate,
            startTime = as.POSIXct(s$startTime))
```

# Epoching

```{r download_events}
download.file("http://cloud.frenchkpi.com/s/wreGqkitWNnWwnP/download", "15012016HD.csv", "wget", T)

hypnogram <- hypnogram(read_events_noxturnal("15012016HD.csv"))
```

```{r epochs}
epochs <- epochs(signals = s$signal,
                 sRates = s$sRate,
                 epoch = hypnogram,
                 startTime = as.numeric(as.POSIXct(s$startTime)))
```

# Periodogram

```{r periodogram, fig.width=7, message=FALSE, error=FALSE}
library(dplyr)
library(ggplot2)

periodograms <- mapply(x = epochs, y = hypnogram$event[-1], FUN = function(x,y){
  periodogram <- phonTools::pwelch(x, fs = s$sRate, show = FALSE)
  periodogram <- as.data.frame(periodogram[periodogram[,1] <= 20,])
  periodogram$stage <- y
  periodogram
}, SIMPLIFY = F)

df <- do.call("rbind", periodograms) %>%
    group_by(hz,stage) %>%
    summarize(dB = mean(dB)) %>%
    ungroup()

ggplot(df, aes(x=hz,y=dB,color=stage)) +
  geom_line() + theme_bw() +
  theme(legend.title = element_blank()) + 
  scale_colour_manual(name = "stage",
                      values = c("#F98400","#F2AD00","#00A08A","#FF0000","#5BBCD6")) +
  xlab("Hertz") + ylab("PSD")

```

# Bands

```{r}

bands <- lapply(epochs,function(x){
  apply(x, 2, function(y){
    bands_power(bands = list(c(0.5,3.5),c(3.5,7.5),c(7.5,13),c(13,30)),
                signal = y, sRate = 200,
                normalize = c(0.5,30))
  })
})



```


# Machine learning

