---
title: "Hypnogram Smoothing"
output: 
  rmarkdown::html_vignette:
     toc: true
     toc_depth: 3
csl: vignettes.csl
bibliography: Hypnogram_Smoothing.bibtex
vignette: >
  %\VignetteIndexEntry{Hypnogram_Smoothing}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

# Creating a hypnogram

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

# Do not run chunks if files are not present.
knitr::opts_chunk$set(
  eval = all(file.exists(
    "15012016HD.edf","15012016HD.csv")))
```

```{r include=FALSE}
devtools::install_github("boupetch/rsleep")
```

```{r setup}
library(rsleep)
```

```{r download_edf, eval=FALSE}
download.file("https://osf.io/57j2u/download", "15012016HD.edf")
```

```{r  download_hypnogram, eval=FALSE}
download.file("https://osf.io/h4ysj/download", "15012016HD.csv")
```

```{r perform_prediction}
hypnodensity <- rsleep::score_psg("15012016HD.edf")
```

# Simple smoothing

```{r smoothing}
smoothed_hypnogram <- hypnodensity

for(i in c(1:5)) 
  smoothed_hypnogram <- rsleep::smooth_hypnogram(smoothed_hypnogram, "N2", "REM",i)
```

```{r plot}
gridExtra::grid.arrange(
  rsleep::plot_hypnogram(rsleep::read_events_noxturnal("15012016HD.csv")) + ggplot2::ggtitle("Visual"),
  rsleep::plot_hypnogram(hypnodensity) + ggplot2::ggtitle("Algorithm"),
  rsleep::plot_hypnogram(smoothed_hypnogram) + ggplot2::ggtitle("Algorithm + Smoothing"),
  nrow = 3)
```

# Liang & Al. smoothing

@liangRulebasedAutomaticSleep2012

```{r}
hypnogram_liang2012 <- rsleep::smooth_liang2012(hypnodensity)

gridExtra::grid.arrange(
  rsleep::plot_hypnogram(rsleep::read_events_noxturnal("15012016HD.csv")) + ggplot2::ggtitle("Visual"),
  rsleep::plot_hypnogram(hypnodensity) + ggplot2::ggtitle("Algorithm"),
  rsleep::plot_hypnogram(hypnogram_liang2012) + ggplot2::ggtitle("Algorithm + Liang 2012 Smoothing"),
  nrow = 3)
```

# References
